defaults: &defaults
  serverengine:
    log: 'STDOUT'
    log_level: 'debug'
    log_rotate_age: 5
    log_rotate_size: 10485760
  triglav:
    url: <%= ENV['TRIGLAV_URL'] || 'http://localhost:7800' %>
    credential:
      username: <%= ENV['TRIGLAV_USERNAME'] || 'triglav_test' %>
      password: <%= ENV['TRIGLAV_PASSWORD'] || 'triglav_test' %>
      authenticator: local
    timeout: 60
    debugging: false
    retries: 3
    retry_interval: 3 # sec
  bigquery:
    monitor_interval: 5
    connection_info:
      "https://bigquery.cloud.google.com/table/<%= ENV['GOOGLE_PROJECT'] || 'your-project' %>":
        # auth_method: # service_account, authorized_user, or compute_engine. default: get type from credentials
        credentials_file: ~/.config/gcloud/application_default_credentials.json
        # credentials: |
        #   {
        #     "private_key_id": "123456789",
        #     "private_key": "-----BEGIN PRIVATE KEY-----\nABCDEF",
        #     "client_email": "..."
        #   }
        retries: 5
        timeout_sec: 300
        open_timeout_sec: 300

development:
  <<: *defaults

test:
  <<: *defaults
